### PR TITLE
Refactor toast window

### PR DESCRIPTION
**Pull request by mgefimov**
Hi, I've refactored the toast window

🎄 Happy Christmas! 🎅

### CODE REVIEW

**Comment by vonovak** [comment]
@mgefimov hello and sorry for forgetting to review this!

Just so it's clear to me - this is just a refactor, so the goal is to do the same thing with less code, do I understand it right?

Thank you!

**Comment by mgefimov** [comment]
@vonovak Hello again!

Yeah, you're right, it's just a refactor. Nothing has changed except the code.

**Comment by vonovak** [comment]
hello, there's a change in behavior for the "toast in alert" example, as seen in the video. It's expected that the toast remains visible.


https://github.com/vonovak/react-native-simple-toast/assets/1566403/ff353438-02d0-4f24-9cbd-9688076ff467

**Comment by mgefimov** [comment]
@vonovak Thank you for the review! I have fixed it.

**Comment by vonovak** [comment]
thank you!
Is there any way to split the changes into two commits? The original one, and the one that fixes the problem I reported? Now because of the squash and force-push, I can't see how the issue was fixed, and I'm curious about the change.. 😄

Or if you want to explain in words, that's also fine :)

**Comment by mgefimov** [comment]
Yeah, I'll split the changes into two commits

**Comment by mgefimov** [comment]
@vonovak Done

**Comment by vonovak** [comment]
thank you! :)

**Pull request merged**
