### PR TITLE
added typescript declarations

### PR DESCRIPTION
**Pull request by kaoDev**
Hey,
I recently used this lib in a TypeScript project and wanted to contribute my declaration files.

Greetings
Kalle

### CODE REVIEW

**Comment by vonovak** [comment]
@i8wu hehe, apparently I cannot do the releases :)

**Comment by i8wu** [comment]
What's your email address? I'll give you npmjs access

**Comment by vonovak** [comment]
It is my github.com username @ Gmail.com

**Comment by i8wu** [comment]
Actually, what's your npmjs username, is it the same as github?

**Comment by vonovak** [comment]
Yes, it is :)

**Comment by i8wu** [comment]
Added.

**Comment by vonovak** [comment]
@kaoDev released in 0.0.7, thanks!

**Pull request merged**
