### PR TITLE
Tap to dismiss

### PR DESCRIPTION
**Pull request by mgefimov**
Tap to dismiss added

### CODE REVIEW

**Comment by mgefimov** [comment]
updated

**Review by vonovak — COMMENTED** [review]
hi! Thanks for the PR.
This makes sense, however, I believe it'd deviate from how the toasts behave on Android.

How about we make this configurable by the last parameter (currently called `styles`, which would be best to rename it), where we could have `tapToDismissEnabled` (or just `tapToDismiss` or something like that, or more universal `dismissMode: 'timeout' | 'tap'` ... something else in the future - probably over-engineered though)?

By default, it'd be false and we need to document that it only works on ios..

wdyt?

**Comment by mgefimov** [comment]
Sure, good point. I'll do it

**Comment by mgefimov** [comment]
updated

**Review by vonovak — APPROVED** [review]

**Comment by vonovak** [comment]
🙂  thank you for the PR!

**Pull request merged**
